// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkZUT5W_CryMmOKeF1JbyJqjy3miZGoq4',
    appId: '1:411965189446:web:8d07cb4e96786718a00947',
    messagingSenderId: '411965189446',
    projectId: 'graduation-project-443c6',
    authDomain: 'graduation-project-443c6.firebaseapp.com',
    storageBucket: 'graduation-project-443c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBS7sKUuSKKZUdHClnQ3RbMRACYhyUw18',
    appId: '1:411965189446:android:aacf0a82f761d4caa00947',
    messagingSenderId: '411965189446',
    projectId: 'graduation-project-443c6',
    storageBucket: 'graduation-project-443c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6aLsfap2tXZ_6OAgaet9gpAk5oYAGEik',
    appId: '1:411965189446:ios:93b750ce3489b33ea00947',
    messagingSenderId: '411965189446',
    projectId: 'graduation-project-443c6',
    storageBucket: 'graduation-project-443c6.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6aLsfap2tXZ_6OAgaet9gpAk5oYAGEik',
    appId: '1:411965189446:ios:93b750ce3489b33ea00947',
    messagingSenderId: '411965189446',
    projectId: 'graduation-project-443c6',
    storageBucket: 'graduation-project-443c6.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkZUT5W_CryMmOKeF1JbyJqjy3miZGoq4',
    appId: '1:411965189446:web:82aac2ca7b1b7645a00947',
    messagingSenderId: '411965189446',
    projectId: 'graduation-project-443c6',
    authDomain: 'graduation-project-443c6.firebaseapp.com',
    storageBucket: 'graduation-project-443c6.appspot.com',
  );
}
